#!/usr/bin/env ruby
# frozen_string_literal: true

require "cronex"

if ARGV.include?("-h") || ARGV.include?("--help")
  puts <<~EOF
    Usage:   cronex [cron_string]
    Example: cronex "*/15 0 1,15 * 1-5 /usr/bin/find"
  EOF
  exit
end

begin
  puts Cronex.parse(*ARGV)
  exit
rescue ArgumentError => e
  abort("** Error occurred: #{e.message}. Get help: cronex --help")
end
